import Image from 'next/image';

import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

import { HiOutlineDotsVertical } from 'react-icons/hi';
import GeneralLayout from '@/components/layout/generalLayout';
import { AddInterestModal } from '@/components/interest/modal/add-interest';
import { InterestCard } from '@/components/interest/interest-card';

function InterestPage() {
  const SeedData = [
    {
      name: 'Football',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
    {
      name: 'Education',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
    {
      name: 'Business',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
    {
      name: 'Art',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
    {
      name: 'Sport',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
    {
      name: 'General',
      tags: [
        'teachersofinstagram',
        'training',
        'life',
        'studyabroad',
        'health',
        'facts',
        'educationmatters',
        'career',
        'upsc',
        'educational',
        'nonprofit',
        'preschool',
        'fun',
        'engineering',
        'studygram',
        'parenting',
        'follow',
        'onlinelearning',
        'studentlife',
        'elearning',
        'entrepreneur',
        'leadership',
        'family',
        'history',
        'support',
        'like',
        'parents',
        'nature',
        'charity',
        'travel',
      ],
    },
  ];
  return (
    <GeneralLayout pageTitle="Interests">
      <hr />
      <div className="flex p-8 gap-8 flex-wrap  h-full">
        <AddInterestModal />
    
        <InterestCard />
      </div>
    </GeneralLayout>
  );
}

export default InterestPage;
